services:
  - type: web
    name: infortom-1
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://infortom.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: infortom-db
          property: connectionString

databases:
  - name: infortom-db
    plan: free

