services:
  - type: web
    name: infortom-1
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://infortom-1.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: infortom-db-2
          property: connectionString
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false

databases:
  - name: infortom-db-2
    plan: free
